config:
  (): colpali_engine.utils.train_colpali_engine_models.ColModelTrainingConfig
  model:
    (): colpali_engine.utils.wrapper.AutoColModelWrapper
    pretrained_model_name_or_path: "bert-base-uncased"
    training_objective: "biencoder" # "biencoder"
    torch_dtype: !ext torch.float16

  dataset_loading_func: !ext colpali_engine.utils.dataset_transformation.load_manu_embeddings

  loss_func:
    (): colpali_engine.loss.colbert_loss.BiEncoderLoss # BiEncoderLoss # ColbertLoss
  max_length: 128
  run_eval: true
  run_train: true
  add_suffix: true
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 1
    max_steps: 10
    per_device_train_batch_size: 8
    gradient_accumulation_steps: 2
    per_device_eval_batch_size: 8
    dataloader_num_workers: 8
    bf16: false
    save_steps: 50
    eval_steps: 50
    eval_strategy: "steps"
    logging_steps: 10
    warmup_steps: 10
    learning_rate: 5e-4
    save_total_limit: 1

  peft_config:
    (): peft.LoraConfig
    r: 16
    lora_alpha: 32
    lora_dropout: 0.05
    bias: "none"
    task_type: "FEATURE_EXTRACTION"