config:
  (): colpali_engine.utils.train_colpali_engine_models.ColModelTrainingConfig
  model:
    (): colpali_engine.utils.wrapper.AutoColModelWrapper
    pretrained_model_name_or_path: "FacebookAI/xlm-roberta-base"

  add_suffix: true
  dataset_loading_func: !ext colpali_engine.utils.dataset_transformation.load_manu_embeddings
  max_length: 256
  run_eval: true
  loss_func:
    (): colpali_engine.loss.colbert_loss.ColbertLoss
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 3
    per_device_train_batch_size: 64
    gradient_accumulation_steps: 2
    per_device_eval_batch_size: 8
    dataloader_num_workers: 8
    # bf16: true
    save_steps: 500
    logging_steps: 50
    warmup_steps: 500
    learning_rate: 5e-5
    save_total_limit: 1
