[project]
name = "mineru-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=0.30.1",
    "magic-pdf[full]>=0.6.1",
]
