wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725921902
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.11.9
      5: 0.17.9
      8:
      - 1
      - 5
      13: darwin-arm64
