wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1725899474
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 19
      - 23
      - 47
      - 61
      4: 3.11.9
      5: 0.17.9
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    visualize:
      curves/Precision-Recall(B):
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: x
            y: y
            class: class
          stringSettings:
            title: Precision-Recall(B)
            x-axis-title: Recall
            y-axis-title: Precision
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: curves/Precision-Recall(B)_table
                fields: []
      curves/F1-Confidence(B):
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: x
            y: y
            class: class
          stringSettings:
            title: F1-Confidence(B)
            x-axis-title: Confidence
            y-axis-title: F1
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: curves/F1-Confidence(B)_table
                fields: []
      curves/Precision-Confidence(B):
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: x
            y: y
            class: class
          stringSettings:
            title: Precision-Confidence(B)
            x-axis-title: Confidence
            y-axis-title: Precision
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: curves/Precision-Confidence(B)_table
                fields: []
      curves/Recall-Confidence(B):
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/area-under-curve/v0
          fieldSettings:
            x: x
            y: y
            class: class
          stringSettings:
            title: Recall-Confidence(B)
            x-axis-title: Confidence
            y-axis-title: Recall
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: curves/Recall-Confidence(B)_table
                fields: []
train:
  desc: null
  value:
    task: detect
    mode: train
    model: yolov8n.pt
    data: ./monte_dataset-1/data.yaml
    epochs: 100
    time: null
    patience: 50
    batch: 16
    imgsz: 640
    save: true
    save_period: 10
    cache: false
    device: mps
    workers: 0
    project: null
    name: character_model10
    exist_ok: false
    pretrained: true
    optimizer: auto
    verbose: true
    seed: 0
    deterministic: true
    single_cls: false
    rect: false
    cos_lr: false
    close_mosaic: 10
    resume: false
    amp: true
    fraction: 1.0
    profile: false
    freeze: null
    multi_scale: false
    overlap_mask: true
    mask_ratio: 4
    dropout: 0.0
    val: true
    split: val
    save_json: false
    save_hybrid: false
    conf: null
    iou: 0.7
    max_det: 300
    half: false
    dnn: false
    plots: true
    source: null
    vid_stride: 1
    stream_buffer: false
    visualize: false
    augment: false
    agnostic_nms: false
    classes: null
    retina_masks: false
    embed: null
    show: false
    save_frames: false
    save_txt: false
    save_conf: false
    save_crop: false
    show_labels: true
    show_conf: true
    show_boxes: true
    line_width: null
    format: torchscript
    keras: false
    optimize: false
    int8: false
    dynamic: false
    simplify: false
    opset: null
    workspace: 4
    nms: false
    lr0: 0.01
    lrf: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.0
    box: 7.5
    cls: 0.5
    dfl: 1.5
    pose: 12.0
    kobj: 1.0
    label_smoothing: 0.0
    nbs: 64
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 0.0
    translate: 0.1
    scale: 0.5
    shear: 0.0
    perspective: 0.0
    flipud: 0.0
    fliplr: 0.5
    mosaic: 1.0
    mixup: 0.0
    copy_paste: 0.0
    auto_augment: randaugment
    erasing: 0.4
    crop_fraction: 1.0
    cfg: null
    tracker: botsort.yaml
    save_dir: /opt/homebrew/runs/detect/character_model10
